"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import {
  ArrowUpRight, Bell, CalendarClock, CheckCircle2, ChevronRight, CircleAlert,
  ClipboardCheck, FileText, FolderOpen, Gauge, Home, Menu, Plus, Search,
  Settings, ShieldCheck, Sun, Users, Wrench, X,
} from "lucide-react";
import type { AdminDashboardData } from "@/data/admin-dashboard";

export type AdminView = "dashboard" | "sistemas" | "mantenimientos" | "documentos" | "clientes";

const navItems = [
  { label: "Resumen", href: "/admin", icon: Home },
  { label: "Sistemas", href: "/admin/sistemas", icon: Gauge },
  { label: "Mantenimientos", href: "/admin/mantenimientos", icon: Wrench },
  { label: "Documentos", href: "/admin/documentos", icon: FolderOpen },
  { label: "Clientes", href: "/admin/clientes", icon: Users },
] as const;

function Sidebar({ open, close }: { open: boolean; close: () => void }) {
  const pathname = usePathname();
  return <><button onClick={close} aria-label="Cerrar menú" className={`fixed inset-0 z-40 bg-stone-950/40 backdrop-blur-sm transition lg:hidden ${open ? "opacity-100" : "pointer-events-none opacity-0"}`} /><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-[#171713] px-4 py-5 text-white transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-8 flex items-center justify-between px-2"><Link href="/admin" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#d6b76f] text-[#171713]"><Sun className="size-5" /></span><span><span className="block text-sm font-semibold tracking-[.18em]">SOLARIS</span><span className="block text-[10px] uppercase tracking-[.16em] text-stone-400">Administración</span></span></Link><button onClick={close} className="p-2 text-stone-400 lg:hidden"><X className="size-5" /></button></div><nav className="space-y-1">{navItems.map(({ label, href, icon: Icon }) => { const active = href === "/admin" ? pathname === href : pathname.startsWith(href); return <Link key={href} href={href} onClick={close} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${active ? "bg-white text-stone-950" : "text-stone-400 hover:bg-white/10 hover:text-white"}`}><Icon className={`size-4 ${active ? "text-[#9b7835]" : ""}`} />{label}</Link>; })}</nav><div className="mt-auto space-y-2"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-stone-400 hover:bg-white/10"><Settings className="size-4" />Configuración</button><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#d6b76f] text-xs font-bold text-stone-900">SM</span><span><span className="block text-sm font-medium">Sergio Martínez</span><span className="block text-xs text-stone-500">Administrador</span></span></div></div></div></aside></>;
}

function Header({ openMenu, title }: { openMenu: () => void; title: string }) { return <header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-stone-200 bg-[#faf9f6]/90 px-5 backdrop-blur-xl md:px-8"><div className="flex items-center gap-3"><button onClick={openMenu} className="grid size-10 place-items-center rounded-xl border border-stone-200 bg-white lg:hidden"><Menu className="size-5" /></button><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#9b7835]">Panel administrativo</p><h1 className="text-lg font-semibold tracking-tight text-stone-900">{title}</h1></div></div><div className="flex items-center gap-2"><button className="relative grid size-10 place-items-center rounded-xl border border-stone-200 bg-white text-stone-500"><Bell className="size-4" /><span className="absolute right-2 top-2 size-2 rounded-full bg-[#b88b3e]" /></button><button className="hidden h-10 items-center gap-2 rounded-xl bg-stone-900 px-4 text-sm font-semibold text-white sm:flex"><Plus className="size-4" />Nuevo sistema</button></div></header>; }

function Status({ value }: { value: string }) { const attention = value === "Requiere atención"; const upcoming = value === "Próximo"; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${attention ? "bg-red-50 text-red-700" : upcoming ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{attention ? <CircleAlert className="size-3" /> : <CheckCircle2 className="size-3" />}{value}</span>; }

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#9b7835]">{eyebrow}</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.035em] text-stone-900 md:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-500">{description}</p></div>; }

function Dashboard({ data, notify }: { data: AdminDashboardData; notify: (m: string) => void }) { const icons = [Gauge, Users, ClipboardCheck, CalendarClock]; return <div className="space-y-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><PageTitle eyebrow="Vista general" title="Buenos días, Sergio" description="Resumen del expediente y los próximos servicios de tus sistemas fotovoltaicos." /><button onClick={() => notify("Formulario disponible en la siguiente fase")} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-stone-900 px-5 text-sm font-semibold text-white"><Plus className="size-4" />Registrar sistema</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric, index) => { const Icon = icons[index]; return <article key={metric.label} className="rounded-3xl border border-stone-200 bg-white p-5 shadow-[0_12px_35px_rgba(28,25,20,.04)]"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-[#f4efe4] text-[#9b7835]"><Icon className="size-5" /></span><ArrowUpRight className="size-4 text-stone-300" /></div><div className="mt-5 text-3xl font-semibold tracking-tight">{metric.value}</div><div className="mt-1 text-sm font-medium text-stone-700">{metric.label}</div><div className="mt-3 text-xs text-stone-400">{metric.change}</div></article>; })}</div><div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><SystemsTable data={data} compact /><article className="rounded-3xl border border-stone-200 bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#9b7835]">Actividad</p><h3 className="mt-1 text-xl font-semibold">Servicios recientes</h3></div><ClipboardCheck className="size-5 text-stone-300" /></div><div className="space-y-5">{data.recentServices.map((service) => <div key={`${service.system}-${service.date}`} className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-emerald-500" /><div className="min-w-0 flex-1"><div className="text-sm font-semibold text-stone-800">{service.type}</div><div className="mt-1 text-xs text-stone-500">{service.system} · {service.client}</div></div><span className="text-xs text-stone-400">{service.date}</span></div>)}</div></article></div></div>; }

function SystemsTable({ data, compact = false }: { data: AdminDashboardData; compact?: boolean }) { const systems = compact ? data.systems.slice(0, 4) : data.systems; return <article className="overflow-hidden rounded-3xl border border-stone-200 bg-white"><div className="flex flex-col gap-4 border-b border-stone-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#9b7835]">Portafolio</p><h3 className="mt-1 text-xl font-semibold">Sistemas fotovoltaicos</h3></div><div className="flex items-center gap-2 rounded-xl border border-stone-200 px-3 py-2 text-stone-400"><Search className="size-4" /><input placeholder="Buscar sistema" className="w-36 bg-transparent text-sm outline-none" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="bg-stone-50 text-[10px] uppercase tracking-[.14em] text-stone-400"><tr><th className="px-5 py-3 font-semibold">Sistema / cliente</th><th className="px-5 py-3 font-semibold">Potencia</th><th className="px-5 py-3 font-semibold">Próximo servicio</th><th className="px-5 py-3 font-semibold">Estado</th><th /></tr></thead><tbody>{systems.map((item) => <tr key={item.id} className="border-t border-stone-100 text-sm"><td className="px-5 py-4"><div className="font-semibold text-stone-900">{item.id}</div><div className="mt-1 text-xs text-stone-500">{item.client} · {item.location}</div></td><td className="px-5 py-4 font-medium text-stone-600">{item.power}</td><td className="px-5 py-4 text-stone-600">{item.nextService}</td><td className="px-5 py-4"><Status value={item.status} /></td><td className="px-5 py-4"><Link href={item.id === "FV-0001" ? `/s/${item.id}` : "/admin/sistemas"} className="grid size-8 place-items-center rounded-lg border border-stone-200 text-stone-400 hover:text-stone-900"><ChevronRight className="size-4" /></Link></td></tr>)}</tbody></table></div>{compact && <Link href="/admin/sistemas" className="flex items-center justify-center gap-2 border-t border-stone-100 py-4 text-sm font-semibold text-stone-600 hover:bg-stone-50">Ver todos los sistemas <ChevronRight className="size-4" /></Link>}</article>; }

function Maintenance({ data }: { data: AdminDashboardData }) { return <div className="space-y-8"><PageTitle eyebrow="Operación" title="Mantenimientos" description="Programa, documenta y consulta los servicios realizados en cada sistema." /><div className="grid gap-4 md:grid-cols-3">{["Programados", "Completados", "Requieren seguimiento"].map((label, i) => <div key={label} className="rounded-3xl border border-stone-200 bg-white p-5"><span className={`grid size-10 place-items-center rounded-2xl ${i === 2 ? "bg-red-50 text-red-600" : "bg-[#f4efe4] text-[#9b7835]"}`}><Wrench className="size-5" /></span><div className="mt-4 text-2xl font-semibold">{[7, 38, 2][i]}</div><div className="mt-1 text-sm text-stone-500">{label}</div></div>)}</div><article className="rounded-3xl border border-stone-200 bg-white p-6"><h3 className="text-xl font-semibold">Actividad reciente</h3><div className="mt-5 divide-y divide-stone-100">{data.recentServices.map(s => <div key={`${s.system}-${s.date}`} className="grid gap-2 py-4 sm:grid-cols-[90px_1fr_160px] sm:items-center"><span className="text-xs text-stone-400">{s.date}</span><div><div className="text-sm font-semibold">{s.type}</div><div className="text-xs text-stone-500">{s.system} · {s.client}</div></div><span className="text-sm text-stone-500">{s.technician}</span></div>)}</div></article></div>; }

function DocumentsView({ data, notify }: { data: AdminDashboardData; notify: (m: string) => void }) { return <div className="space-y-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><PageTitle eyebrow="Archivos" title="Documentos" description="Reportes, fotografías y documentación técnica vinculada a cada expediente." /><button onClick={() => notify("Carga de archivos disponible en la siguiente fase")} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-stone-900 px-5 text-sm font-semibold text-white"><Plus className="size-4" />Subir documento</button></div><div className="grid gap-4 md:grid-cols-3">{data.documents.map(doc => <article key={doc.name} className="rounded-3xl border border-stone-200 bg-white p-5"><span className="grid size-11 place-items-center rounded-2xl bg-[#f4efe4] text-[#9b7835]"><FileText className="size-5" /></span><h3 className="mt-5 text-sm font-semibold">{doc.name}</h3><p className="mt-1 text-xs text-stone-400">{doc.system} · {doc.type}</p><p className="mt-5 border-t border-stone-100 pt-4 text-xs text-stone-500">{doc.date}</p></article>)}</div></div>; }

function Clients({ data }: { data: AdminDashboardData }) { return <div className="space-y-8"><PageTitle eyebrow="Directorio" title="Clientes" description="Información básica de propietarios y relación con sus sistemas registrados." /><div className="grid gap-4 lg:grid-cols-2">{data.clients.map(client => <article key={client.name} className="flex items-center gap-4 rounded-3xl border border-stone-200 bg-white p-5"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-stone-900 font-semibold text-[#d6b76f]">{client.name.split(" ").slice(-1)[0].slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><h3 className="font-semibold">{client.name}</h3><p className="mt-1 truncate text-xs text-stone-500">{client.contact}</p><p className="mt-2 text-xs text-stone-400">{client.systems} sistema(s) · Último servicio: {client.lastService}</p></div><ChevronRight className="size-4 text-stone-300" /></article>)}</div></div>; }

export function AdminPortal({ data, view = "dashboard" }: { data: AdminDashboardData; view?: AdminView }) { const [menu, setMenu] = useState(false); const [toast, setToast] = useState(""); const titles = { dashboard: "Resumen", sistemas: "Sistemas", mantenimientos: "Mantenimientos", documentos: "Documentos", clientes: "Clientes" }; const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); }; return <div className="min-h-screen bg-[#faf9f6] text-stone-900"><Sidebar open={menu} close={() => setMenu(false)} /><div className="lg:pl-72"><Header openMenu={() => setMenu(true)} title={titles[view]} /><main className="mx-auto max-w-[1500px] px-5 py-8 md:px-8 md:py-10">{view === "dashboard" && <Dashboard data={data} notify={notify} />}{view === "sistemas" && <div className="space-y-8"><PageTitle eyebrow="Portafolio" title="Sistemas fotovoltaicos" description="Consulta y administra los expedientes de todos los sistemas registrados." /><SystemsTable data={data} /></div>}{view === "mantenimientos" && <Maintenance data={data} />}{view === "documentos" && <DocumentsView data={data} notify={notify} />}{view === "clientes" && <Clients data={data} />}</main></div>{toast && <div role="status" className="fixed bottom-6 left-1/2 z-[60] -translate-x-1/2 rounded-full bg-stone-900 px-5 py-3 text-sm font-medium text-white shadow-xl">{toast}</div>}</div>; }
